(define-module (mlg notelist)
  :use-module (srfi srfi-1)
  :use-module (srfi srfi-11)
  :use-module (rnrs io ports)
  :use-module (mlg binports)
  :use-module (ice-9 pretty-print)
  :use-module (ice-9 optargs)
  :export (
           note-time
           note-duration
           note-channel
           note-key
           note-patch
           note-percussion
           note-velocity-begin
           note-velocity-end
           note-pitch-bend

           MidiEvents->NoteList
           NormalizeNoteListTimes!))

;; The final information for a note, after all the mergin, is this...
(define (note-time n) (list-ref n 0))
(define (note-duration n) (list-ref n 1))
(define (note-key n) (list-ref n 2))
(define (note-patch n) (list-ref n 3))
(define (note-percussion n) (list-ref n 4))
(define (note-velocity-begin n) (list-ref n 5))
(define (note-velocity-end n) (list-ref n 6))
(define (note-pitch-bend n) (list-ref n 7))

(define (set-note-time! n v)
  (list-set! n 0 v))
(define (set-note-duration! n v)
  (list-set! n 1 v))

;; We'll use the term 'tone generator' for the structure that stores
;; a note for which an ON has been received, but no OFF yet.
;; The Track+Key combination is a unique identifier for a tone generator.

;; TG assoc list
;; 0. time
;; 1. key
;; 2. patch
;; 3. percussion
;; 4. velocity
;; 5. pitch bend

(define (make-tg-hash track key)
  (logior (ash track 8) key))
(define (tg-time x) (first x))
(define (tg-key x) (second x))
(define (tg-patch x) (third x))
(define (tg-percussion x) (fourth x))
(define (tg-velocity x) (fifth x))
(define (tg-pitch-bend x) (sixth x))

(define (MidiEvents->NoteList midiEvents)
  "Given a MIDI events list as generated by ParseMidi(), 
search for pairs of NOTE_ON and NOTE_OFF events and convert them
to a list of notes with durations.  Also, look for PROGRAM_CHANGE
events that assign instruments and PITCH_WHEEL events."

  (define (_IsNoteOn x)
    (eqv? 'NOTE_ON (car x)))
  (define (_IsNoteOff x)
    (eqv? 'NOTE_OFF (car x)))
  (define (_IsProgramChange x)
    (eqv? 'PROGRAM_CHANGE (car x)))
  (define (_IsPitchWheel x)
    (eqv? 'PITCH_WHEEL (car x)))
  (define (_IsAllNotesOff x)
    (eqv? 'ALL_NOTES_OFF (car x)))

  (let (;; Current instrument for each channel
        [_patch (make-list 16 0)]
        ;; Current pitch bend for each channel (8192 = no bend)
        [_pitchBend (make-list 16 8192)]
        ;; List of note-started events
        [toneList '()]
        ;; Return value
        [noteList '()])
    (do ([i 0 (1+ i)]) ([= i (length midiEvents)])
      (let ([event (list-ref midiEvents i)])
        (cond
         ;; FIXME: handle ALL_NOTES_OFF here.
         [(or (_IsNoteOn event) (_IsNoteOff event))
          (let-keywords (cdr event) #t (time track channel key velocity)
                        (if (and (_IsNoteOn event) (> velocity 0))
                            (set! toneList
                                  (assoc-set! toneList (make-tg-hash track key)
                                              (list time
                                                    key
                                                    (list-ref _patch channel) ; last PROGRAM_CHANGE instrument received
                                                    (eqv? channel 9) ; channel 9 is percussion
                                                    velocity
                                                    (list-ref _pitchBend channel)))) ; current pitch bend
                            ;; else OFF event
                            (let ([tonegen (assoc-ref toneList (make-tg-hash track key))])
                              (when tonegen
                                    (set! noteList
                                          (append
                                           noteList
                                           (list
                                            (list
                                             (tg-time tonegen)
                                             (- time (tg-time tonegen)) ; duration
                                             key
                                             (tg-patch tonegen)
                                             (tg-percussion tonegen)
                                             (tg-velocity tonegen) ; start velocity
                                             velocity              ; end velocity
                                             (tg-pitch-bend tonegen)       ; pitch bend
                                             ))))
                                    (set! toneList
                                          (assoc-remove! toneList (make-tg-hash track key)))))))]

         [(_IsProgramChange event)
          (let-keywords (cdr event) #t (channel patch)
                        (list-set! _patch channel patch))]
         
         [(_IsPitchWheel event)
          (let-keywords (cdr event) #t (channel value)
                        (list-set! _pitchBend channel value))])))
    noteList))

(define (NormalizeNoteListTimes! noteList ticksPerQuarterNote tempoMap)
  "Given a note list as generated by MidiEvents->NoteList and a tempo
map as generated by MidiEvents->TempoMap, this modifies the times in
noteList from MIDI ticks to microseconds, properly handling tempo changes."
  
  (letrec ((_TickToSeconds
            (lambda (targetTick)
              "Convert a tick value to seconds, accounting for tempo changes."
              (if (or (null? tempoMap) (= (length tempoMap) 0))
                  ;; Default tempo: 120 BPM = 500000 microseconds per quarter note
                  (let ([msPerTick (exact->inexact (/ 500000 ticksPerQuarterNote))])
                    (* targetTick msPerTick 1e-6))
                  ;; else: walk through tempo changes
                  (let loop ([currentTick 0]
                             [timeInSeconds 0.0]
                             [tempoIdx 0])
                    (if (>= tempoIdx (length tempoMap))
                        ;; Beyond all tempo changes, use the last tempo
                        (let* ([lastTempo (cdr (list-ref tempoMap (1- (length tempoMap))))]
                               [msPerTick (exact->inexact (/ lastTempo ticksPerQuarterNote))]
                               [ticksRemaining (- targetTick currentTick)])
                          (+ timeInSeconds (* ticksRemaining msPerTick 1e-6)))
                        ;; Process tempo segments
                        (let* ([currentTempoEntry (list-ref tempoMap tempoIdx)]
                               [currentTempoValue (cdr currentTempoEntry)])
                          ;; Determine the end of this tempo segment
                          (let ([segmentEndTick (if (< tempoIdx (1- (length tempoMap)))
                                                    (car (list-ref tempoMap (1+ tempoIdx)))
                                                    targetTick)])
                            (if (<= targetTick segmentEndTick)
                                ;; Target is within this tempo segment
                                (let* ([ticksInSegment (- targetTick currentTick)]
                                       [msPerTick (exact->inexact (/ currentTempoValue ticksPerQuarterNote))]
                                       [segmentTime (* ticksInSegment msPerTick 1e-6)])
                                  (+ timeInSeconds segmentTime))
                                ;; Target is beyond this segment, process and continue
                                (let* ([ticksInSegment (- segmentEndTick currentTick)]
                                       [msPerTick (exact->inexact (/ currentTempoValue ticksPerQuarterNote))]
                                       [segmentTime (* ticksInSegment msPerTick 1e-6)])
                                  (loop segmentEndTick
                                        (+ timeInSeconds segmentTime)
                                        (1+ tempoIdx))))))))))))
    
    (for-each
     (lambda (note)
       (let ([startTick (note-time note)]
             [durationTicks (note-duration note)])
         (let ([startTime (_TickToSeconds startTick)]
               [endTime (_TickToSeconds (+ startTick durationTicks))])
           (set-note-time! note startTime)
           (set-note-duration! note (- endTime startTime)))))
     noteList)))
